/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './__root'
import { Route as IndexRouteImport } from './index'
import { Route as privatePrivateLayoutRouteImport } from './(private)/_privateLayout'
import { Route as authSingupRouteImport } from './(auth)/singup'
import { Route as authLoginRouteImport } from './(auth)/login'
import { Route as privatePrivateLayoutDashboardRouteImport } from './(private)/_privateLayout.dashboard'

const privateRouteImport = createFileRoute('/(private)')()

const privateRoute = privateRouteImport.update({
  id: '/(private)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const privatePrivateLayoutRoute = privatePrivateLayoutRouteImport.update({
  id: '/_privateLayout',
  getParentRoute: () => privateRoute,
} as any)
const authSingupRoute = authSingupRouteImport.update({
  id: '/(auth)/singup',
  path: '/singup',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const privatePrivateLayoutDashboardRoute =
  privatePrivateLayoutDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => privatePrivateLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof privatePrivateLayoutRouteWithChildren
  '/login': typeof authLoginRoute
  '/singup': typeof authSingupRoute
  '/dashboard': typeof privatePrivateLayoutDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof privatePrivateLayoutRouteWithChildren
  '/login': typeof authLoginRoute
  '/singup': typeof authSingupRoute
  '/dashboard': typeof privatePrivateLayoutDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/singup': typeof authSingupRoute
  '/(private)': typeof privateRouteWithChildren
  '/(private)/_privateLayout': typeof privatePrivateLayoutRouteWithChildren
  '/(private)/_privateLayout/dashboard': typeof privatePrivateLayoutDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/singup' | '/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/singup' | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/(auth)/login'
    | '/(auth)/singup'
    | '/(private)'
    | '/(private)/_privateLayout'
    | '/(private)/_privateLayout/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authLoginRoute: typeof authLoginRoute
  authSingupRoute: typeof authSingupRoute
  privateRoute: typeof privateRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(private)': {
      id: '/(private)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof privateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/_privateLayout': {
      id: '/(private)/_privateLayout'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof privatePrivateLayoutRouteImport
      parentRoute: typeof privateRoute
    }
    '/(auth)/singup': {
      id: '/(auth)/singup'
      path: '/singup'
      fullPath: '/singup'
      preLoaderRoute: typeof authSingupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/_privateLayout/dashboard': {
      id: '/(private)/_privateLayout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof privatePrivateLayoutDashboardRouteImport
      parentRoute: typeof privatePrivateLayoutRoute
    }
  }
}

interface privatePrivateLayoutRouteChildren {
  privatePrivateLayoutDashboardRoute: typeof privatePrivateLayoutDashboardRoute
}

const privatePrivateLayoutRouteChildren: privatePrivateLayoutRouteChildren = {
  privatePrivateLayoutDashboardRoute: privatePrivateLayoutDashboardRoute,
}

const privatePrivateLayoutRouteWithChildren =
  privatePrivateLayoutRoute._addFileChildren(privatePrivateLayoutRouteChildren)

interface privateRouteChildren {
  privatePrivateLayoutRoute: typeof privatePrivateLayoutRouteWithChildren
}

const privateRouteChildren: privateRouteChildren = {
  privatePrivateLayoutRoute: privatePrivateLayoutRouteWithChildren,
}

const privateRouteWithChildren =
  privateRoute._addFileChildren(privateRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authLoginRoute: authLoginRoute,
  authSingupRoute: authSingupRoute,
  privateRoute: privateRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
